### ISSUE TITLE
Velocity Support

### ISSUE THREAD

**Issue by RealTriassic** [arkflame/ChatSentinel#10]
Velocity is a Minecraft: Java Edition Proxy - more information about it at https://velocitypowered.com/

I believe that ChatSentinel having Velocity support would be really great as Velocity has been growing really quickly recently and having more great plugins such as ChatSentinel natively available on Velocity would be really good!

**Comment by chrismwiggs** [comment]
Bumping this now that Velocity is part of the Paper team and waterfall has been deprecated in favour of Velocity. Will see more and more demand for Velocity support, would be awesome to get in front of it!
