### ISSUE TITLE
incompatibility with LibertyBans

### ISSUE THREAD

**Issue by ghost** [arkflame/ChatSentinel#42]
When fake-message option is enabled and I write something forbidden and I get mute for 3 tries and then I write unmute my_name and I still can't write. Server on 1.8.8 PandaSpigot 
Tested on LibertyBans plugin
("mute %player% 1d Offensive Language (%message%)")

**Comment by F3F5** [comment]
This is latest build cb2cbb81f504a147363484b9636d9c0867f1c81e

**Comment by F3F5** [comment]
even when I'm in a mutha, the plugin checks for spam.
