### ISSUE TITLE
Aternos compability

### ISSUE THREAD

**Issue by hero23550** [arkflame/ChatSentinel#43]
This is the best free chat moderation plugin so far I have used. Please come to Aternos too, most of the chat moderation plugin available there don't have as much features as this does!

Aternos in this [article](https://support.aternos.org/hc/en-us/articles/360052255311-Suggesting-new-mods-plugins-and-modpacks#h_01EPF9S3W42P6KV2P5YJ9FSF6T)
States that they only support plugins (for java mc) from modrinth, spigot ,curseforge and bukkit. Would be fantastic if you considered my request and uploaded this plugin to one of the websites.

**Comment by linsaftw** [comment]
Added to my personal todo list.
