### ISSUE TITLE
notifications problem

### ISSUE THREAD

**Issue by ghost** [arkflame/ChatSentinel#45]
![Screenshot_13](https://github.com/arkflame/ChatSentinel/assets/108226177/cb63a75f-ea48-464c-a46a-3a83bd2a6c6e)
why do I see alerts (this: CS: MichaelKozlov failed Swearing (fuck)) if I don't have perms, and even if I turn off "" in the settings, I still see

**Comment by F3F5** [comment]
It seems to be a problem after the recode

**Comment by linsaftw** [comment]
> ![Screenshot_13](https://private-user-images.githubusercontent.com/108226177/333119824-cb63a75f-ea48-464c-a46a-3a83bd2a6c6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1ODgxOTMsIm5iZiI6MTcxNjU4Nzg5MywicGF0aCI6Ii8xMDgyMjYxNzcvMzMzMTE5ODI0LWNiNjNhNzVmLWVhNDgtNDY0Yy1hNDZhLTNhODNiZDJhNmM2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQyMTU4MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODA5MTZlNDQwM2ZhOTlhMWFiZTk2ODgxNTIwMWMxY2U4MzIxYTQ5MDQ1ZmM0Y2I0M2M5MjRjZDNlOWJmZTVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hwIBybPg2tGxE1T9jLpOzLRr-FM8p49peA_pKv5BzP0) why do I see alerts (this: CS: MichaelKozlov failed Swearing (fuck)) if I don't have perms, and even if I turn off "" in the settings, I still see

Hi, alerts depend on the language setup of the server. Does the same issue happen in the older updates? Please test again.

**Comment by F3F5** [comment]
@linsaftw 
![Screenshot_1](https://github.com/arkflame/ChatSentinel/assets/170719238/0abc50f8-b2d9-4e1d-adca-f73fddcee781)
![Screenshot_2](https://github.com/arkflame/ChatSentinel/assets/170719238/85a9052e-45f0-464c-96fa-15119112e2b0)

**Comment by linsaftw** [comment]
> @linsaftw ![Screenshot_1](https://private-user-images.githubusercontent.com/170719238/346662298-0abc50f8-b2d9-4e1d-adca-f73fddcee781.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MzA5NzMsIm5iZiI6MTcyMDUzMDY3MywicGF0aCI6Ii8xNzA3MTkyMzgvMzQ2NjYyMjk4LTBhYmM1MGY4LWIyZDktNGUxZC1hZGNhLWY3M2ZkZGNlZTc4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxMzExMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OWNlOTg5YWVlODg4M2U5MGRmODkzZmVmNjhjNjhiZmM0YjE0YjcxMWJhMjUwMTk1MmY4ZmJmNDU0NWRhNjdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PXcb61tLB73y6iuL9MvV_YJ9TibBB8ayqL2e865o3WA) ![Screenshot_2](https://private-user-images.githubusercontent.com/170719238/346662425-85a9052e-45f0-464c-96fa-15119112e2b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MzA5NzMsIm5iZiI6MTcyMDUzMDY3MywicGF0aCI6Ii8xNzA3MTkyMzgvMzQ2NjYyNDI1LTg1YTkwNTJlLTQ1ZjAtNDY0Yy05NmZhLTE1MTE5MTEyZTJiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxMzExMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTk0MWFmZjVhMzIzY2QxYjBhYzE5N2UxZDk5YmVhNjQ4ODg3YzJhYjZmMWI4Mjc2NjE1NjdlZjdjZGYxNzQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.saZtKgT44p8O6pHfUAJjrnB1zGFtYxCIxGmqO3hKpuU)

Thank you

**Comment by F3F5** [comment]
> > @linsaftw ![Screenshot_1](https://private-user-images.githubusercontent.com/170719238/346662298-0abc50f8-b2d9-4e1d-adca-f73fddcee781.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MzA5NzMsIm5iZiI6MTcyMDUzMDY3MywicGF0aCI6Ii8xNzA3MTkyMzgvMzQ2NjYyMjk4LTBhYmM1MGY4LWIyZDktNGUxZC1hZGNhLWY3M2ZkZGNlZTc4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxMzExMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OWNlOTg5YWVlODg4M2U5MGRmODkzZmVmNjhjNjhiZmM0YjE0YjcxMWJhMjUwMTk1MmY4ZmJmNDU0NWRhNjdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PXcb61tLB73y6iuL9MvV_YJ9TibBB8ayqL2e865o3WA) ![Screenshot_2](https://private-user-images.githubusercontent.com/170719238/346662425-85a9052e-45f0-464c-96fa-15119112e2b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MzA5NzMsIm5iZiI6MTcyMDUzMDY3MywicGF0aCI6Ii8xNzA3MTkyMzgvMzQ2NjYyNDI1LTg1YTkwNTJlLTQ1ZjAtNDY0Yy05NmZhLTE1MTE5MTEyZTJiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxMzExMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTk0MWFmZjVhMzIzY2QxYjBhYzE5N2UxZDk5YmVhNjQ4ODg3YzJhYjZmMWI4Mjc2NjE1NjdlZjdjZGYxNzQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.saZtKgT44p8O6pHfUAJjrnB1zGFtYxCIxGmqO3hKpuU)
> 
> Thank you

why closed :(

**Comment by linsaftw** [comment]
> ![Screenshot_13](https://private-user-images.githubusercontent.com/108226177/333119824-cb63a75f-ea48-464c-a46a-3a83bd2a6c6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTE1ODEsIm5iZiI6MTcyMDYxMTI4MSwicGF0aCI6Ii8xMDgyMjYxNzcvMzMzMTE5ODI0LWNiNjNhNzVmLWVhNDgtNDY0Yy1hNDZhLTNhODNiZDJhNmM2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQxMTM0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTJjZjQxNDhiM2ZkNzMzNzVlNDBiZDhhMzZiYzMzMDM3ZWIxOGQwOTQzY2VjOGMzMmRhMTZiNjRhZGVjNWQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kPPvQHtVqRqrTJ_LSTMIxHpPwypdhKSAL3R3coUEymQ) why do I see alerts (this: CS: MichaelKozlov failed Swearing (fuck)) if I don't have perms, and even if I turn off "" in the settings, I still see

The notification is the "failed swearing" not the red ones. It's disabled properly and you shown his issue does not exist.

**Comment by F3F5** [comment]
> > ![Screenshot_13](https://private-user-images.githubusercontent.com/108226177/333119824-cb63a75f-ea48-464c-a46a-3a83bd2a6c6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTE1ODEsIm5iZiI6MTcyMDYxMTI4MSwicGF0aCI6Ii8xMDgyMjYxNzcvMzMzMTE5ODI0LWNiNjNhNzVmLWVhNDgtNDY0Yy1hNDZhLTNhODNiZDJhNmM2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQxMTM0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTJjZjQxNDhiM2ZkNzMzNzVlNDBiZDhhMzZiYzMzMDM3ZWIxOGQwOTQzY2VjOGMzMmRhMTZiNjRhZGVjNWQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kPPvQHtVqRqrTJ_LSTMIxHpPwypdhKSAL3R3coUEymQ) why do I see alerts (this: CS: MichaelKozlov failed Swearing (fuck)) if I don't have perms, and even if I turn off "" in the settings, I still see
> 
> The notification is the "failed swearing" not the red ones. It's disabled properly and you shown his issue does not exist. If you want to customize the others, use the language file.
so I can't remove the extra notification like in the old version
failed swearing for example.

**Comment by linsaftw** [comment]
> > > ![Screenshot_13](https://private-user-images.githubusercontent.com/108226177/333119824-cb63a75f-ea48-464c-a46a-3a83bd2a6c6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTE1ODEsIm5iZiI6MTcyMDYxMTI4MSwicGF0aCI6Ii8xMDgyMjYxNzcvMzMzMTE5ODI0LWNiNjNhNzVmLWVhNDgtNDY0Yy1hNDZhLTNhODNiZDJhNmM2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQxMTM0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTJjZjQxNDhiM2ZkNzMzNzVlNDBiZDhhMzZiYzMzMDM3ZWIxOGQwOTQzY2VjOGMzMmRhMTZiNjRhZGVjNWQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kPPvQHtVqRqrTJ_LSTMIxHpPwypdhKSAL3R3coUEymQ) why do I see alerts (this: CS: MichaelKozlov failed Swearing (fuck)) if I don't have perms, and even if I turn off "" in the settings, I still see
> > 
> > 
> > The notification is the "failed swearing" not the red ones. It's disabled properly and you shown his issue does not exist. If you want to customize the others, use the language file.
> 
> so I can't remove the extra notification like in the old version failed swearing for example.

You did disable the one the user reported. To remove the other ones, which was never possible, you can set the message to empty in the messages.yml.

**Comment by F3F5** [comment]
4-1? lmfao

**Comment by F3F5** [comment]
I'm not going to prove to the author lol , it says make "" to remove the line , I did - it didn't remove, in the old version it did remove
The author is toxic, and I won't be dialoguing with him.

**Comment by linsaftw** [comment]
> I'm not going to prove to the author lol , it says make "" to remove the line , I did - it didn't remove, in the old version it did remove so i can't disable useless warn message 4/-1

The notification removes the "Failed swearing" not the red messages.

**Comment by F3F5** [comment]
![Screenshot_24](https://github.com/user-attachments/assets/6b4db2a5-90e4-4c20-8a89-2c4d4593a2ad)
this can't.

**Comment by linsaftw** [comment]
> ![Screenshot_24](https://private-user-images.githubusercontent.com/170719238/348534720-6b4db2a5-90e4-4c20-8a89-2c4d4593a2ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0OTQ3MjQsIm5iZiI6MTcyMTQ5NDQyNCwicGF0aCI6Ii8xNzA3MTkyMzgvMzQ4NTM0NzIwLTZiNGRiMmE1LTkwZTQtNGMyMC04YTg5LTJjNGQ0NTkzYTJhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQxNjUzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mY2VhMGRmMTIxZGQyMjMxZDJiODZiYmMwMTY1Y2VhNjFiMWVlMjMzNmU3M2QzZWJlMDMyNGZkNjhmMmU2NDUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qrriX4D_7EcAjSkgMRD0UyH8cutk5D8TF-nu7CJCLAw) this can't.

This is NOT in the config.yml. This is on messages.yml.

**Comment by linsaftw** [comment]
messages.yml

    blacklist_warn_message: "&c&lCS: &cYou cant type '%message%'! (%warns%/%maxwarns%)"
